### PR TITLE
Upload of Kharaa surface water bodies shapefile

### PR DESCRIPTION
**Pull request by vanbremer**
Uploaded 02_surface_water_bodies_32648.shp to geoportal. Again, the GeoServer did not show the uploaded file afterwards, but we will keep adding further data soon!

### CODE REVIEW

**Comment by marcjansen** [comment]
@paulsen, can you have a look at this issue?

**Comment by vanbremer** [comment]
@paulsen, please ignore this layer for now ( 02_surface_water_bodies_32648.shp), we will upload a new version with minor corrections next week!

**Comment by paulsen** [comment]
please deliver new data when you're ready

**Comment by vanbremer** [comment]
@paulsen, just uploaded the corrected version 02_surface_water_bodies_corr_32648.shp,
sorry for the trouble!

**Pull request merged**
