### PR TITLE
Merge remote-tracking branch 'refs/remotes/terrestris/master'

### PR DESCRIPTION
**Pull request by batchimeg-a**
new file 20151216

### CODE REVIEW

**Comment by marcjansen** [comment]
Hey @batchimeg008, do you want to create the new meeting notes file? It isn't currently included in this pull request (PR). Just ping me if you need any help.

**Comment by batchimeg-a** [comment]
hi, I'm doing at homework

**Comment by marcjansen** [comment]
OK, works for me.

**Comment by marcjansen** [comment]
This PR is still empty (see e.g. the tab "Files changed 0"). Will you add s.th. to this PR?

**Comment by paulsen** [comment]
merged this PR to clean up the repository

**Pull request merged**
